# Generated by Django 4.2.4 on 2024-01-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Series_Library', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('number', 'season', 'series')},
        ),
    ]
