# Generated by Django 4.2.4 on 2024-01-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Series_Library', '0002_alter_episode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TV_Series_Library.series'),
        ),
    ]
